add missing canonical "import path" support

diff --git a/go-build b/go-build
--- a/go-build
+++ b/go-build
@@ -15,6 +15,15 @@ fi
 
 dir="$(pwd -P)"
 if [ "$goDir" ]; then
+    goPath="${GOPATH%%:*}" # this just grabs the first path listed in GOPATH, if there are multiple (which is the detection logic "go get" itself uses, too)
+    goDirPath="$goPath/src/$goDir"
+    mkdir -p "$(dirname "$goDirPath")"
+    if [ ! -e "$goDirPath" ]; then
+        ln -sfv "$dir" "$goDirPath"
+    elif [ ! -L "$goDirPath" ]; then
+        echo >&2 "error: $goDirPath already exists but is unexpectedly not a symlink!"
+        exit 1
+    fi
     goBin="/bin/$(basename "$goDir")"
 else
     goBin="/bin/$(basename "$dir")" # likely "app"
